parserOptions:
  ecmaVersion: 2017
  sourceType: 'module'

env:
  es6: true
  browser: true
  commonjs: true
  jquery: true

rules:
  no-invalid-this: 'off'
  guard-for-in: 'off'
  new-cap:
    - error
    - properties: false

globals:
  mediaQuery: readonly

extends: 'htmlacademy/es6'
